window.CATALOG = {
  "title": "Estancia La Taba",
  "subtitle": "Catálogo de muebles y objetos",
  "updated": "2026-09-24",
  "updatedLabel": "24 de septiembre de 2026",
  "rooms": [
    {
      "name": "Dormitorio 2",
      "slug": "dormitorio-2"
    },
    {
      "name": "Dormitorio 3",
      "slug": "dormitorio-3"
    },
    {
      "name": "Dormitorio 4",
      "slug": "dormitorio-4"
    },
    {
      "name": "Dormitorio 5",
      "slug": "dormitorio-5"
    },
    {
      "name": "Dormitorio 6",
      "slug": "dormitorio-6"
    },
    {
      "name": "Dormitorio 7",
      "slug": "dormitorio-7"
    },
    {
      "name": "Dormitorio 8",
      "slug": "dormitorio-8"
    },
    {
      "name": "Living altillo",
      "slug": "living-altillo"
    },
    {
      "name": "Dormitorio 9",
      "slug": "dormitorio-9"
    },
    {
      "name": "Dormitorio 10",
      "slug": "dormitorio-10"
    },
    {
      "name": "Dormitorio principal",
      "slug": "dormitorio-principal"
    },
    {
      "name": "Living secundario",
      "slug": "living-secundario"
    },
    {
      "name": "Living principal",
      "slug": "living-principal"
    },
    {
      "name": "Salón de juegos",
      "slug": "salon-de-juegos"
    },
    {
      "name": "Recibidor",
      "slug": "recibidor"
    },
    {
      "name": "Comedor principal",
      "slug": "comedor-principal"
    },
    {
      "name": "Sector bar",
      "slug": "sector-bar"
    },
    {
      "name": "Lavadero",
      "slug": "lavadero"
    },
    {
      "name": "Galería",
      "slug": "galeria"
    },
    {
      "name": "Cocina",
      "slug": "cocina"
    },
    {
      "name": "Jardín / Parque",
      "slug": "jardin-parque"
    },
    {
      "name": "Fogón",
      "slug": "fogon"
    }
  ],
  "items": [
    {
      "id": "EST-001",
      "room": "Dormitorio 2",
      "roomSlug": "dormitorio-2",
      "category": "Muebles",
      "name": "Sommier 2 Plazas",
      "description": "Sommier en buen estado",
      "quantity": 1,
      "measures": "2 Plazas",
      "condition": null,
      "price": 350000,
      "status": "Disponible",
      "image": "images/items/EST-001.jpg"
    },
    {
      "id": "EST-002",
      "room": "Dormitorio 2",
      "roomSlug": "dormitorio-2",
      "category": "Muebles",
      "name": "Respaldo negro",
      "description": "Respaldo negro en perfecto estado",
      "quantity": 1,
      "measures": "2 Plazas",
      "condition": "Buen estado",
      "price": 60000,
      "status": "Disponible",
      "image": "images/items/EST-002.jpg"
    },
    {
      "id": "EST-003",
      "room": "Dormitorio 2",
      "roomSlug": "dormitorio-2",
      "category": "Muebles",
      "name": "Mesa de luz Blanca",
      "description": "Comoda con cajon blanca",
      "quantity": 1,
      "measures": "43x31x65",
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-003.jpg"
    },
    {
      "id": "EST-004",
      "room": "Dormitorio 2",
      "roomSlug": "dormitorio-2",
      "category": "Muebles",
      "name": "Mesa de luz Blanca",
      "description": "Comoda con cajon blanca",
      "quantity": 1,
      "measures": "43x31x65",
      "condition": "Despintada",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-004.jpg"
    },
    {
      "id": "EST-005",
      "room": "Dormitorio 2",
      "roomSlug": "dormitorio-2",
      "category": "Iluminación",
      "name": "Velador artesanal",
      "description": "Velador artesanal",
      "quantity": 2,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-005.jpg"
    },
    {
      "id": "EST-006",
      "room": "Dormitorio 2",
      "roomSlug": "dormitorio-2",
      "category": "Cuadros de caballos",
      "name": "Cuadro caballo blanco",
      "description": "Cuadro caballo grande",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-006.jpg"
    },
    {
      "id": "EST-007",
      "room": "Dormitorio 2",
      "roomSlug": "dormitorio-2",
      "category": "Muebles",
      "name": "Cuna + Cambiador + Cajonera",
      "description": "Cuna con colchon, cambiador y cajones",
      "quantity": 1,
      "measures": null,
      "condition": "Sin detalles",
      "price": 250000,
      "status": "Disponible",
      "image": "images/items/EST-007.jpg"
    },
    {
      "id": "EST-008",
      "room": "Dormitorio 2",
      "roomSlug": "dormitorio-2",
      "category": "Muebles",
      "name": "Escritorio",
      "description": "Escritorio blanco con cajones",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 120000,
      "status": "Disponible",
      "image": "images/items/EST-008.jpg"
    },
    {
      "id": "EST-009",
      "room": "Dormitorio 2",
      "roomSlug": "dormitorio-2",
      "category": "Muebles",
      "name": "Sillon Matero de un cuerpo",
      "description": "Un cuerpo color beige",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 150000,
      "status": "Disponible",
      "image": "images/items/EST-009.jpg"
    },
    {
      "id": "EST-010",
      "room": "Dormitorio 2",
      "roomSlug": "dormitorio-2",
      "category": "Electrodomésticos",
      "name": "TV Admiral 32'",
      "description": "TV 32' Admiral",
      "quantity": 1,
      "measures": "32'",
      "condition": "Buen estado",
      "price": 150000,
      "status": "Disponible",
      "image": "images/items/EST-010.jpg"
    },
    {
      "id": "EST-011",
      "room": "Dormitorio 2",
      "roomSlug": "dormitorio-2",
      "category": "Electrodomésticos",
      "name": "Estufa electrica ATMA",
      "description": "Estufa atma con ruedas",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 120000,
      "status": "Disponible",
      "image": "images/items/EST-011.jpg"
    },
    {
      "id": "EST-012",
      "room": "Dormitorio 3",
      "roomSlug": "dormitorio-3",
      "category": "Muebles",
      "name": "Mesa de luz blanca",
      "description": "Comoda con cajon blanca",
      "quantity": 1,
      "measures": "43x31x65",
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-012.jpg"
    },
    {
      "id": "EST-013",
      "room": "Dormitorio 3",
      "roomSlug": "dormitorio-3",
      "category": "Iluminación",
      "name": "Velador artesanal",
      "description": "Velador artesanal",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-013.jpg"
    },
    {
      "id": "EST-015",
      "room": "Dormitorio 4",
      "roomSlug": "dormitorio-4",
      "category": "Muebles",
      "name": "Mesa de luz blanca",
      "description": "Comoda con cajon blanca",
      "quantity": 1,
      "measures": "43x31x65",
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-015.jpg"
    },
    {
      "id": "EST-016",
      "room": "Dormitorio 4",
      "roomSlug": "dormitorio-4",
      "category": "Iluminación",
      "name": "Velador artesanal",
      "description": "Velador artesanal de hierro con campana",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-016.jpg"
    },
    {
      "id": "EST-017",
      "room": "Dormitorio 4",
      "roomSlug": "dormitorio-4",
      "category": "Cuadros de animales",
      "name": "Cuadro Conejo",
      "description": "Cuadro conejo",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": "images/items/EST-017.jpg"
    },
    {
      "id": "EST-018",
      "room": "Dormitorio 4",
      "roomSlug": "dormitorio-4",
      "category": "Muebles",
      "name": "Cama de Hierro negro 1 Plaza + colchon",
      "description": "cama de hierro negro mas colchon en buen estado",
      "quantity": 2,
      "measures": "1 Plaza",
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": "images/items/EST-018.jpg"
    },
    {
      "id": "EST-019",
      "room": "Dormitorio 5",
      "roomSlug": "dormitorio-5",
      "category": "Muebles",
      "name": "Mesa de luz blanca",
      "description": "Comoda con cajon blanca",
      "quantity": 2,
      "measures": "43x31x65",
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-019.jpg"
    },
    {
      "id": "EST-020",
      "room": "Dormitorio 5",
      "roomSlug": "dormitorio-5",
      "category": "Muebles",
      "name": "Sommier 2 Plazas",
      "description": "Sommier 2P en buen estado",
      "quantity": 1,
      "measures": "2 Plazas",
      "condition": "Buen estado",
      "price": 350000,
      "status": "Disponible",
      "image": "images/items/EST-020.jpg"
    },
    {
      "id": "EST-021",
      "room": "Dormitorio 5",
      "roomSlug": "dormitorio-5",
      "category": "Iluminación",
      "name": "Velador artesanal",
      "description": "Velador artesanal",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-021.jpg"
    },
    {
      "id": "EST-022",
      "room": "Dormitorio 5",
      "roomSlug": "dormitorio-5",
      "category": "Electrodomésticos",
      "name": "Estufa electrica ATMA",
      "description": "Estufa atma con ruedas",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 120000,
      "status": "Disponible",
      "image": "images/items/EST-022.jpg"
    },
    {
      "id": "EST-023",
      "room": "Dormitorio 5",
      "roomSlug": "dormitorio-5",
      "category": "Iluminación",
      "name": "Aplique de pared rustico",
      "description": "Aplique de pared con tirador",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-023.jpg"
    },
    {
      "id": "EST-024",
      "room": "Dormitorio 6",
      "roomSlug": "dormitorio-6",
      "category": "Muebles",
      "name": "Cama de madera 1 Plaza",
      "description": "Cama de madera 1 Plaza con respaldo",
      "quantity": 2,
      "measures": "1 Plaza",
      "condition": "Buen estado",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-024.jpg"
    },
    {
      "id": "EST-025",
      "room": "Dormitorio 6",
      "roomSlug": "dormitorio-6",
      "category": "Muebles",
      "name": "Mesa de luz Blanca chica",
      "description": "Mesa de luz blanca chica",
      "quantity": 1,
      "measures": "35x30x60",
      "condition": "Despintada",
      "price": 35000,
      "status": "Disponible",
      "image": "images/items/EST-025.jpg"
    },
    {
      "id": "EST-026",
      "room": "Dormitorio 6",
      "roomSlug": "dormitorio-6",
      "category": "Iluminación",
      "name": "Velador",
      "description": "Velador artesanal",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-026.jpg"
    },
    {
      "id": "EST-027",
      "room": "Dormitorio 6",
      "roomSlug": "dormitorio-6",
      "category": "Cuadros de animales",
      "name": "Cuadro oveja",
      "description": "Cuadro de oveja",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-027.jpg"
    },
    {
      "id": "EST-028",
      "room": "Dormitorio 7",
      "roomSlug": "dormitorio-7",
      "category": "Muebles",
      "name": "Cama de madera 1 Plaza",
      "description": "Cama de madera 1 Plaza con respaldo",
      "quantity": 2,
      "measures": "1 Plaza",
      "condition": "Buen estado",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-028.jpg"
    },
    {
      "id": "EST-029",
      "room": "Dormitorio 7",
      "roomSlug": "dormitorio-7",
      "category": "Muebles",
      "name": "Mesa de luz blanca",
      "description": "Mesa de luz blanca con cajon",
      "quantity": 1,
      "measures": "43x31x65",
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-029.jpg"
    },
    {
      "id": "EST-030",
      "room": "Dormitorio 7",
      "roomSlug": "dormitorio-7",
      "category": "Iluminación",
      "name": "Velador artesanal",
      "description": "Velador artesanal de hierro con campana",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-030.jpg"
    },
    {
      "id": "EST-031",
      "room": "Dormitorio 7",
      "roomSlug": "dormitorio-7",
      "category": "Cuadros de animales",
      "name": "Cuadro vaca",
      "description": "Cuadro de vaca marco de madera",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-031.jpg"
    },
    {
      "id": "EST-032",
      "room": "Dormitorio 8",
      "roomSlug": "dormitorio-8",
      "category": "Muebles",
      "name": "Cama de madera 1 plaza con camastro y 3 cajones",
      "description": "Cama de 1 plaza con camastro y 3 cajones",
      "quantity": 1,
      "measures": "1 Plaza",
      "condition": "Buen estado",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-032.jpg"
    },
    {
      "id": "EST-033",
      "room": "Dormitorio 8",
      "roomSlug": "dormitorio-8",
      "category": "Muebles",
      "name": "Cama de hierro 1 Plaza",
      "description": "Cama con base de hierro 1 Plaza",
      "quantity": 1,
      "measures": "1 Plaza",
      "condition": "Buen estado",
      "price": 120000,
      "status": "Disponible",
      "image": "images/items/EST-033.jpg"
    },
    {
      "id": "EST-034",
      "room": "Dormitorio 8",
      "roomSlug": "dormitorio-8",
      "category": "Muebles",
      "name": "Cofre de madera blanco",
      "description": "Cofre de madera",
      "quantity": 1,
      "measures": "50x50x50",
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-034.jpg"
    },
    {
      "id": "EST-035",
      "room": "Dormitorio 8",
      "roomSlug": "dormitorio-8",
      "category": "Cuadros de animales",
      "name": "Cuadro oveja",
      "description": "Cuadro de oveja marco de madera",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-035.jpg"
    },
    {
      "id": "EST-036",
      "room": "Living altillo",
      "roomSlug": "living-altillo",
      "category": "Muebles",
      "name": "Sillon cama verde",
      "description": "Sillon cama verde plegable",
      "quantity": 1,
      "measures": null,
      "condition": "Roto pero funcional",
      "price": 120000,
      "status": "Disponible",
      "image": "images/items/EST-036.jpg"
    },
    {
      "id": "EST-037",
      "room": "Living altillo",
      "roomSlug": "living-altillo",
      "category": "Muebles",
      "name": "Sillon cama amarillo",
      "description": "Sillon cama amarillo plegable",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 150000,
      "status": "Disponible",
      "image": "images/items/EST-037.jpg"
    },
    {
      "id": "EST-038",
      "room": "Living altillo",
      "roomSlug": "living-altillo",
      "category": "Muebles",
      "name": "Mesa ratona de madera",
      "description": "Mesa ratona de madera",
      "quantity": 1,
      "measures": "100x60x40",
      "condition": "Buen estado",
      "price": 80000,
      "status": "Disponible",
      "image": "images/items/EST-038.jpg"
    },
    {
      "id": "EST-039",
      "room": "Living altillo",
      "roomSlug": "living-altillo",
      "category": "Cuadros de caballos",
      "name": "Cuadro caballos amanecer",
      "description": "Cuadro caballos amanecer",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-039.jpg"
    },
    {
      "id": "EST-040",
      "room": "Dormitorio 9",
      "roomSlug": "dormitorio-9",
      "category": "Muebles",
      "name": "Sommier 2 Plazas",
      "description": "Cama sommier 2 Plazas",
      "quantity": 1,
      "measures": "2 Plazas",
      "condition": "Buen estado",
      "price": 350000,
      "status": "Disponible",
      "image": "images/items/EST-040.jpg"
    },
    {
      "id": "EST-041",
      "room": "Dormitorio 9",
      "roomSlug": "dormitorio-9",
      "category": "Muebles",
      "name": "Respaldo 2 Plazas negro",
      "description": "Respaldo negro en perfecto estado",
      "quantity": 1,
      "measures": "2 Plazas",
      "condition": "Buen estado",
      "price": 60000,
      "status": "Disponible",
      "image": "images/items/EST-041.jpg"
    },
    {
      "id": "EST-042",
      "room": "Dormitorio 9",
      "roomSlug": "dormitorio-9",
      "category": "Muebles",
      "name": "Mesa de luz blanca",
      "description": "Mesa de luz blanca con cajon",
      "quantity": 1,
      "measures": "43x31x65",
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-042.jpg"
    },
    {
      "id": "EST-043",
      "room": "Dormitorio 9",
      "roomSlug": "dormitorio-9",
      "category": "Muebles",
      "name": "Mesa de luz blanca",
      "description": "Mesa de luz blanca con cajon",
      "quantity": 1,
      "measures": "43x31x65",
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-043.jpg"
    },
    {
      "id": "EST-044",
      "room": "Dormitorio 9",
      "roomSlug": "dormitorio-9",
      "category": "Iluminación",
      "name": "Velador artesanal",
      "description": "Velador artesanal de hierro con campana",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-044.jpg"
    },
    {
      "id": "EST-045",
      "room": "Dormitorio 9",
      "roomSlug": "dormitorio-9",
      "category": "Iluminación",
      "name": "Velador artesanal",
      "description": "Velador artesanal de hierro con campana",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-045.jpg"
    },
    {
      "id": "EST-046",
      "room": "Dormitorio 9",
      "roomSlug": "dormitorio-9",
      "category": "Cuadros de caballos",
      "name": "Cuadro caballo",
      "description": "Cuadro de caballo blanco",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-046.jpg"
    },
    {
      "id": "EST-047",
      "room": "Dormitorio 9",
      "roomSlug": "dormitorio-9",
      "category": "Muebles",
      "name": "Sillon matero de un cuerpo",
      "description": "Sillon matero rojo 1 cuerpo",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 150000,
      "status": "Disponible",
      "image": "images/items/EST-047.jpg"
    },
    {
      "id": "EST-048",
      "room": "Dormitorio 10",
      "roomSlug": "dormitorio-10",
      "category": "Muebles",
      "name": "Sommier 2 Plazas",
      "description": "Cama sommier 2 Plazas",
      "quantity": 1,
      "measures": "2 Plazas",
      "condition": "Buen estado",
      "price": 350000,
      "status": "Disponible",
      "image": "images/items/EST-048.jpg"
    },
    {
      "id": "EST-049",
      "room": "Dormitorio 10",
      "roomSlug": "dormitorio-10",
      "category": "Muebles",
      "name": "Mesa de luz Blanca",
      "description": "Mesa de luz blanca con cajon",
      "quantity": 2,
      "measures": "43x31x65",
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-049.jpg"
    },
    {
      "id": "EST-050",
      "room": "Dormitorio 10",
      "roomSlug": "dormitorio-10",
      "category": "Iluminación",
      "name": "Velador artesanal",
      "description": "Velador artesanal de hierro con campana",
      "quantity": 2,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-050.jpg"
    },
    {
      "id": "EST-051",
      "room": "Dormitorio 10",
      "roomSlug": "dormitorio-10",
      "category": "Muebles",
      "name": "Respaldo 2 Plazas negro",
      "description": "Respaldo negro en perfecto estado",
      "quantity": 1,
      "measures": "2 Plazas",
      "condition": "Buen estado",
      "price": 60000,
      "status": "Disponible",
      "image": "images/items/EST-051.jpg"
    },
    {
      "id": "EST-052",
      "room": "Dormitorio 10",
      "roomSlug": "dormitorio-10",
      "category": "Cuadros de caballos",
      "name": "Cuadro caballos amanecer",
      "description": "Cuadro caballos amanecer",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-052.jpg"
    },
    {
      "id": "EST-053",
      "room": "Dormitorio principal",
      "roomSlug": "dormitorio-principal",
      "category": "Muebles",
      "name": "Sommier 2 Plazas",
      "description": "Cama sommier 2 Plazas",
      "quantity": 1,
      "measures": "2 Plazas",
      "condition": "Buen estado",
      "price": 350000,
      "status": "Disponible",
      "image": "images/items/EST-053.jpg"
    },
    {
      "id": "EST-054",
      "room": "Dormitorio principal",
      "roomSlug": "dormitorio-principal",
      "category": "Muebles",
      "name": "Respaldo 2 Plazas negro",
      "description": "Respaldo negro en perfecto estado",
      "quantity": 1,
      "measures": "2 Plazas",
      "condition": "Buen estado",
      "price": 60000,
      "status": "Disponible",
      "image": "images/items/EST-054.jpg"
    },
    {
      "id": "EST-055",
      "room": "Dormitorio principal",
      "roomSlug": "dormitorio-principal",
      "category": "Muebles",
      "name": "Mesa de luz",
      "description": "Mesa de luz blanca con cajon",
      "quantity": 1,
      "measures": "43x31x65",
      "condition": "Despintada",
      "price": 35000,
      "status": "Disponible",
      "image": "images/items/EST-055.jpg"
    },
    {
      "id": "EST-056",
      "room": "Dormitorio principal",
      "roomSlug": "dormitorio-principal",
      "category": "Muebles",
      "name": "Mesa de luz",
      "description": "Mesa de luz blanca con cajon",
      "quantity": 1,
      "measures": "43x31x66",
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-056.jpg"
    },
    {
      "id": "EST-057",
      "room": "Dormitorio principal",
      "roomSlug": "dormitorio-principal",
      "category": "Iluminación",
      "name": "Velador artesanal",
      "description": "Velador artesanal de hierro con campana",
      "quantity": 2,
      "measures": null,
      "condition": "Buen estado",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-057.jpg"
    },
    {
      "id": "EST-058",
      "room": "Dormitorio principal",
      "roomSlug": "dormitorio-principal",
      "category": "Cuadros de caballos",
      "name": "Cuadro caballo",
      "description": "Cuadro de caballo",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-058.jpg"
    },
    {
      "id": "EST-059",
      "room": "Dormitorio principal",
      "roomSlug": "dormitorio-principal",
      "category": "Muebles",
      "name": "Sillon matero gris",
      "description": "Sillon matero gris 1 cuerpo",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 150000,
      "status": "Disponible",
      "image": "images/items/EST-059.jpg"
    },
    {
      "id": "EST-060",
      "room": "Dormitorio principal",
      "roomSlug": "dormitorio-principal",
      "category": "Electrodomésticos",
      "name": "Estufa electrica ATMA",
      "description": "Estufa atma con ruedas",
      "quantity": 2,
      "measures": null,
      "condition": "Buen estado",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-060.jpg"
    },
    {
      "id": "EST-061",
      "room": "Living secundario",
      "roomSlug": "living-secundario",
      "category": "Muebles",
      "name": "Cama de mimbre y colchon",
      "description": "Cama de mimbre con colchon",
      "quantity": 1,
      "measures": "1 Plaza",
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-061.jpg"
    },
    {
      "id": "EST-062",
      "room": "Living secundario",
      "roomSlug": "living-secundario",
      "category": "Muebles",
      "name": "Sillon cama azul",
      "description": "Sillon cama azul",
      "quantity": 1,
      "measures": "2 M",
      "condition": "Buen estado",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-062.jpg"
    },
    {
      "id": "EST-063",
      "room": "Living secundario",
      "roomSlug": "living-secundario",
      "category": "Muebles",
      "name": "Mesa de madera chica",
      "description": "Mesa ratona de madera",
      "quantity": 1,
      "measures": "90x1.50x38",
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-063.jpg"
    },
    {
      "id": "EST-064",
      "room": "Living secundario",
      "roomSlug": "living-secundario",
      "category": "Iluminación",
      "name": "Velador de pie",
      "description": "Velador de pie",
      "quantity": 1,
      "measures": null,
      "condition": "Probar devuelta no lo pude hacer funcionar",
      "price": 30000,
      "status": "Disponible",
      "image": "images/items/EST-064.jpg"
    },
    {
      "id": "EST-065",
      "room": "Living secundario",
      "roomSlug": "living-secundario",
      "category": "Cuadros de caballos",
      "name": "Cuadro caballo",
      "description": "Cuadro de caballos",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-065.jpg"
    },
    {
      "id": "EST-066",
      "room": "Living principal",
      "roomSlug": "living-principal",
      "category": "Muebles",
      "name": "Sillon 3 cuerpos cuero",
      "description": "Sillon 3 cuerpos cuero marron",
      "quantity": 1,
      "measures": "2.10 M",
      "condition": "Pata rota cuero en buen estado",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-066.jpg"
    },
    {
      "id": "EST-067",
      "room": "Living principal",
      "roomSlug": "living-principal",
      "category": "Muebles",
      "name": "Sillon 1 cuerpo cuero",
      "description": "Sillon 1 cuerpo cuero marron",
      "quantity": 2,
      "measures": "1 cuerpo",
      "condition": "1 roto en apoya brazo",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-067.jpg"
    },
    {
      "id": "EST-068",
      "room": "Living principal",
      "roomSlug": "living-principal",
      "category": "Muebles",
      "name": "Perchero de madera",
      "description": "Perchero de madera 5",
      "quantity": 1,
      "measures": "60cm",
      "condition": "Buen estado",
      "price": 30000,
      "status": "Disponible",
      "image": "images/items/EST-068.jpg"
    },
    {
      "id": "EST-069",
      "room": "Living principal",
      "roomSlug": "living-principal",
      "category": "Cuadros de caballos",
      "name": "Cuadro caballo",
      "description": "Multiples cuadros de caballos",
      "quantity": 6,
      "measures": null,
      "condition": "Buen estado",
      "price": 600000,
      "status": "Disponible",
      "image": "images/items/EST-069-1.jpg",
      "images": [
        "images/items/EST-069-1.jpg",
        "images/items/EST-069-2.jpg",
        "images/items/EST-069-3.jpg",
        "images/items/EST-069-4.jpg",
        "images/items/EST-069-5.jpg",
        "images/items/EST-069-6.jpg"
      ]
    },
    {
      "id": "EST-070",
      "room": "Living principal",
      "roomSlug": "living-principal",
      "category": "Muebles",
      "name": "Mesa ratona de vidrio",
      "description": "Mesa ratona cuadrada de vidrio",
      "quantity": 1,
      "measures": "1x1",
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-070.jpg"
    },
    {
      "id": "EST-071",
      "room": "Salón de juegos",
      "roomSlug": "salon-de-juegos",
      "category": "Muebles",
      "name": "Sillones 2 cuerpos azul",
      "description": "Sillon azul dos cuerpos",
      "quantity": 3,
      "measures": "2 cuerpos",
      "condition": "Buen estado",
      "price": 1000000,
      "status": "Disponible",
      "image": "images/items/EST-071.jpg"
    },
    {
      "id": "EST-072",
      "room": "Salón de juegos",
      "roomSlug": "salon-de-juegos",
      "category": "Muebles",
      "name": "Mesa ratona de madera",
      "description": "Mesa ratona de madera",
      "quantity": 1,
      "measures": "1.40x83x50",
      "condition": "Buen estado",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-072.jpg"
    },
    {
      "id": "EST-073",
      "room": "Salón de juegos",
      "roomSlug": "salon-de-juegos",
      "category": "Juegos",
      "name": "Mesa de ping pong",
      "description": "Mesa de ping pong",
      "quantity": 1,
      "measures": "2.73x1.53x75",
      "condition": "Buen estado",
      "price": 400000,
      "status": "Disponible",
      "image": "images/items/EST-073.jpg"
    },
    {
      "id": "EST-074",
      "room": "Salón de juegos",
      "roomSlug": "salon-de-juegos",
      "category": "Juegos",
      "name": "Metegol",
      "description": "Metegol",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-074.jpg"
    },
    {
      "id": "EST-075",
      "room": "Salón de juegos",
      "roomSlug": "salon-de-juegos",
      "category": "Iluminación",
      "name": "Lampara de pie",
      "description": "Lampara de pie",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 30000,
      "status": "Disponible",
      "image": "images/items/EST-075.jpg"
    },
    {
      "id": "EST-076",
      "room": "Salón de juegos",
      "roomSlug": "salon-de-juegos",
      "category": "Muebles",
      "name": "Mueble rustico",
      "description": "Mueble de madera rustico",
      "quantity": 1,
      "measures": "200x100x50",
      "condition": "Buen estado",
      "price": 150000,
      "status": "Disponible",
      "image": "images/items/EST-076.jpg"
    },
    {
      "id": "EST-078",
      "room": "Recibidor",
      "roomSlug": "recibidor",
      "category": "Muebles",
      "name": "Sillon 3 cuerpos floreado",
      "description": "Sillon 3 cuerpos floreado",
      "quantity": 1,
      "measures": "1.90x70",
      "condition": "Buen estado",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-078.jpg"
    },
    {
      "id": "EST-079",
      "room": "Recibidor",
      "roomSlug": "recibidor",
      "category": "Muebles",
      "name": "Perchero de madera largo",
      "description": "Perchero de madera 10",
      "quantity": 1,
      "measures": "1 M",
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-079.jpg"
    },
    {
      "id": "EST-080",
      "room": "Recibidor",
      "roomSlug": "recibidor",
      "category": "Cuadros de caballos",
      "name": "Cuadro caballo",
      "description": "Cuadro caballo grande",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-080.jpg"
    },
    {
      "id": "EST-083",
      "room": "Comedor principal",
      "roomSlug": "comedor-principal",
      "category": "Muebles",
      "name": "Mesa de madera grande 14 sillas",
      "description": "Mesa de madera grande con 14 sillas",
      "quantity": 1,
      "measures": "3x1.20",
      "condition": "Buen estado",
      "price": 400000,
      "status": "Disponible",
      "image": "images/items/EST-083.jpg"
    },
    {
      "id": "EST-084",
      "room": "Comedor principal",
      "roomSlug": "comedor-principal",
      "category": "Muebles",
      "name": "Mesa de apoyo de madera",
      "description": "Mesa de apoyo de madera",
      "quantity": 1,
      "measures": "2x1",
      "condition": "Buen estado",
      "price": 250000,
      "status": "Disponible",
      "image": "images/items/EST-084.jpg"
    },
    {
      "id": "EST-085",
      "room": "Comedor principal",
      "roomSlug": "comedor-principal",
      "category": "Muebles",
      "name": "Mueble de apoyo vintage",
      "description": "Mueble de apoyo vintage",
      "quantity": 1,
      "measures": "1.5x2.3.65",
      "condition": "Buen estado",
      "price": 350000,
      "status": "Disponible",
      "image": "images/items/EST-085.jpg"
    },
    {
      "id": "EST-088",
      "room": "Sector bar",
      "roomSlug": "sector-bar",
      "category": "Muebles",
      "name": "Mesa redonda madera grande",
      "description": "Mesa redonda de madera",
      "quantity": 1,
      "measures": "1.20",
      "condition": "Buen estado",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-088.jpg"
    },
    {
      "id": "EST-089",
      "room": "Sector bar",
      "roomSlug": "sector-bar",
      "category": "Muebles",
      "name": "Sillas X5",
      "description": "Sillas de madera",
      "quantity": 5,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-089.jpg"
    },
    {
      "id": "EST-090",
      "room": "Sector bar",
      "roomSlug": "sector-bar",
      "category": "Muebles",
      "name": "Banquetas barra",
      "description": "Banquetas de madera barra",
      "quantity": 3,
      "measures": null,
      "condition": "Buen estado",
      "price": 75000,
      "status": "Disponible",
      "image": "images/items/EST-090.jpg"
    },
    {
      "id": "EST-091",
      "room": "Sector bar",
      "roomSlug": "sector-bar",
      "category": "Estufa",
      "name": "Tromen grande",
      "description": "Tromen grande",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 600000,
      "status": "Disponible",
      "image": "images/items/EST-091.jpg"
    },
    {
      "id": "EST-094",
      "room": "Lavadero",
      "roomSlug": "lavadero",
      "category": "Electrodomésticos",
      "name": "Lavarropas LG",
      "description": "Lavarropas LG 8.5KG",
      "quantity": 1,
      "measures": "60x57x85",
      "condition": "Un poco oxidado funciona",
      "price": 450000,
      "status": "Disponible",
      "image": "images/items/EST-094.jpg"
    },
    {
      "id": "EST-095",
      "room": "Lavadero",
      "roomSlug": "lavadero",
      "category": "Electrodomésticos",
      "name": "Lavarropas Drean",
      "description": "Lavarropas Drean 8.12KG",
      "quantity": 1,
      "measures": "60x55x85",
      "condition": "Buen estado",
      "price": 250000,
      "status": "Disponible",
      "image": "images/items/EST-095.jpg"
    },
    {
      "id": "EST-096",
      "room": "Lavadero",
      "roomSlug": "lavadero",
      "category": "Electrodomésticos",
      "name": "Lavarropas Drean",
      "description": "Lavarropas Drean 8.12KG",
      "quantity": 2,
      "measures": "60x55x85",
      "condition": "Un poco oxidado funciona",
      "price": 250000,
      "status": "Disponible",
      "image": "images/items/EST-096.jpg"
    },
    {
      "id": "EST-097",
      "room": "Lavadero",
      "roomSlug": "lavadero",
      "category": "Electrodomésticos",
      "name": "Lavarrolas Eslabon de Lujo",
      "description": "Lavarropas eslabon 7KG",
      "quantity": 1,
      "measures": "60x55x85",
      "condition": "Buen estado",
      "price": 250000,
      "status": "Disponible",
      "image": "images/items/EST-097.jpg"
    },
    {
      "id": "EST-098",
      "room": "Lavadero",
      "roomSlug": "lavadero",
      "category": "Electrodomésticos",
      "name": "Secadora Philco",
      "description": "Secadora fuera de servicio",
      "quantity": 1,
      "measures": "60x55x85",
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": "images/items/EST-098.jpg"
    },
    {
      "id": "EST-099",
      "room": "Lavadero",
      "roomSlug": "lavadero",
      "category": "Textiles",
      "name": "Sabanas blancas 1P",
      "description": "Sabanas blancas 1P",
      "quantity": 48,
      "measures": "1 Plaza",
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": "images/items/EST-099.jpg"
    },
    {
      "id": "EST-100",
      "room": "Lavadero",
      "roomSlug": "lavadero",
      "category": "Textiles",
      "name": "Sabanas blancas 2P",
      "description": "Sabanas blancas 2P",
      "quantity": 24,
      "measures": "2 Plazas",
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": "images/items/EST-100.jpg"
    },
    {
      "id": "EST-101",
      "room": "Lavadero",
      "roomSlug": "lavadero",
      "category": "Textiles",
      "name": "Toalla de mano",
      "description": "Toallas de mano blancas",
      "quantity": 20,
      "measures": null,
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": "images/items/EST-101.jpg"
    },
    {
      "id": "EST-102",
      "room": "Lavadero",
      "roomSlug": "lavadero",
      "category": "Textiles",
      "name": "Sabanas de cuna",
      "description": "Sabanas de cuna",
      "quantity": 2,
      "measures": null,
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": null
    },
    {
      "id": "EST-103",
      "room": "Lavadero",
      "roomSlug": "lavadero",
      "category": "Textiles",
      "name": "Toallones blancos",
      "description": "Toallones blancos",
      "quantity": 40,
      "measures": null,
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": "images/items/EST-103.jpg"
    },
    {
      "id": "EST-104",
      "room": "Lavadero",
      "roomSlug": "lavadero",
      "category": "Textiles",
      "name": "Repasadores",
      "description": "Repasadores",
      "quantity": 23,
      "measures": null,
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": "images/items/EST-104.jpg"
    },
    {
      "id": "EST-105",
      "room": "Lavadero",
      "roomSlug": "lavadero",
      "category": "Textiles",
      "name": "Alfombra ducha",
      "description": "Alfombra de baño",
      "quantity": 4,
      "measures": null,
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": null
    },
    {
      "id": "EST-108",
      "room": "Galería",
      "roomSlug": "galeria",
      "category": "Muebles",
      "name": "Mesa de hierro negra",
      "description": "mesa de hierro negra 10 Personas",
      "quantity": 1,
      "measures": "2.5x1.50",
      "condition": "Buen estado",
      "price": 600000,
      "status": "Disponible",
      "image": "images/items/EST-108.jpg"
    },
    {
      "id": "EST-109",
      "room": "Galería",
      "roomSlug": "galeria",
      "category": "Muebles",
      "name": "Mesa y silllas vintage con almohadones",
      "description": "Mesa y sillas vintage",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 400000,
      "status": "Disponible",
      "image": "images/items/EST-109.jpg"
    },
    {
      "id": "EST-144",
      "room": "Galería",
      "roomSlug": "galeria",
      "category": "Muebles",
      "name": "Silloncitos de plastico",
      "description": "Sillon de jardin de plastico",
      "quantity": 4,
      "measures": null,
      "condition": null,
      "price": 350000,
      "status": "Disponible",
      "image": "images/items/EST-144.jpg"
    },
    {
      "id": "EST-112",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Vajilla",
      "name": "Vasos de vidrio",
      "description": "Vasos de vidrio",
      "quantity": 26,
      "measures": null,
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": "images/items/EST-112.jpg"
    },
    {
      "id": "EST-113",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Vajilla",
      "name": "Copas de agua",
      "description": "Copas de agua",
      "quantity": 40,
      "measures": null,
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": "images/items/EST-113.jpg"
    },
    {
      "id": "EST-114",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Vajilla",
      "name": "Jarras de vidrio",
      "description": "Jarras de vidrio",
      "quantity": 3,
      "measures": null,
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": "images/items/EST-114.jpg"
    },
    {
      "id": "EST-115",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Vajilla",
      "name": "Jarras de plastico",
      "description": "Jarras de plastico",
      "quantity": 2,
      "measures": null,
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": "images/items/EST-115.jpg"
    },
    {
      "id": "EST-116",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Vajilla",
      "name": "vasos de plastico",
      "description": "vasos de plastico celestes",
      "quantity": 20,
      "measures": null,
      "condition": "Buen estado",
      "price": null,
      "status": "Disponible",
      "image": "images/items/EST-116.jpg"
    },
    {
      "id": "EST-117",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Vajilla",
      "name": "Vajilla Platos",
      "description": "Juego de vajilla 6 platos y cazuela",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 1000000,
      "status": "Disponible",
      "image": "images/items/EST-117.jpg"
    },
    {
      "id": "EST-118",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Vajilla",
      "name": "Fuentes de vidrio",
      "description": "5 fuentes de vidrio",
      "quantity": 5,
      "measures": null,
      "condition": "Buen estado",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-118.jpg"
    },
    {
      "id": "EST-119",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Vajilla",
      "name": "Utencillos cocina",
      "description": "2 rayadores 2 coladores 1 rayador de queso 1 batidor 1 espatula metal 1cuchillo parrilla 1 cuchara fideos",
      "quantity": 9,
      "measures": null,
      "condition": "Buen estado",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-119.jpg"
    },
    {
      "id": "EST-120",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Vajilla",
      "name": "Tarteras y flanera",
      "description": "3 tarteras 1 flanera",
      "quantity": 3,
      "measures": null,
      "condition": "Buen estado",
      "price": 60000,
      "status": "Disponible",
      "image": "images/items/EST-120.jpg"
    },
    {
      "id": "EST-121",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Vajilla",
      "name": "Cubiertos",
      "description": "34 Tenedores 33 cuchillos 28 Cucharitas 30 Cucharas",
      "quantity": 125,
      "measures": null,
      "condition": "Buen estado",
      "price": 150000,
      "status": "Disponible",
      "image": "images/items/EST-121.jpg"
    },
    {
      "id": "EST-122",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Cocina",
      "name": "Pizzera madera",
      "description": "Pizzera de madera",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 15000,
      "status": "Disponible",
      "image": "images/items/EST-122.jpg"
    },
    {
      "id": "EST-123",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Cocina",
      "name": "4 Fuentes de asado",
      "description": "4 Fuentes de asado metal",
      "quantity": 4,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": "Disponible",
      "image": "images/items/EST-123.jpg"
    },
    {
      "id": "EST-124",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Cocina",
      "name": "Tabla de madera herradura",
      "description": "Tabla de madera para picada",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-124.jpg"
    },
    {
      "id": "EST-125",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Cocina",
      "name": "Ollas Mediana y Grande",
      "description": "2 ollas",
      "quantity": 2,
      "measures": null,
      "condition": "Regular",
      "price": 35000,
      "status": "Disponible",
      "image": null
    },
    {
      "id": "EST-126",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Cocina",
      "name": "1 Fuente",
      "description": "Fuente grande para horno",
      "quantity": 1,
      "measures": "60x50",
      "condition": "Buen estado",
      "price": 80000,
      "status": "Disponible",
      "image": "images/items/EST-126.jpg"
    },
    {
      "id": "EST-127",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Electrodomésticos",
      "name": "Heladera Philco",
      "description": "Heladera philco",
      "quantity": 1,
      "measures": "58.5x61x1.81",
      "condition": "Como nueva",
      "price": 150000,
      "status": "Disponible",
      "image": "images/items/EST-127.jpg"
    },
    {
      "id": "EST-128",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Electrodomésticos",
      "name": "Heladera LG",
      "description": "Heladera LG",
      "quantity": 1,
      "measures": "60x63x1.65",
      "condition": "Como nueva",
      "price": 150000,
      "status": "Disponible",
      "image": "images/items/EST-128.jpg"
    },
    {
      "id": "EST-129",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Electrodomésticos",
      "name": "Frizzer Whirlpool",
      "description": "Frezzer Whirlpool",
      "quantity": 1,
      "measures": "62x62x1.54",
      "condition": "Como nuevo",
      "price": 150000,
      "status": "Disponible",
      "image": "images/items/EST-129.jpg"
    },
    {
      "id": "EST-130",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Electrodomésticos",
      "name": "Tostadora Peabody",
      "description": "Tostadora cuatro panes",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 20000,
      "status": "Disponible",
      "image": "images/items/EST-130.jpg"
    },
    {
      "id": "EST-131",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Electrodomésticos",
      "name": "Microondas BGH",
      "description": "Microondas BGH",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-131.jpg"
    },
    {
      "id": "EST-132",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Electrodomésticos",
      "name": "Cafetera Lilana",
      "description": "Cafetera Liliana COFLY",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 20000,
      "status": "Disponible",
      "image": "images/items/EST-132.jpg"
    },
    {
      "id": "EST-133",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Electrodomésticos",
      "name": "Pava electrica",
      "description": "Pava electrica",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 20000,
      "status": "Disponible",
      "image": null
    },
    {
      "id": "EST-134",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Muebles",
      "name": "Mesa de vidrio y ratan",
      "description": "Mesa de vidrio circular",
      "quantity": 1,
      "measures": "1.20",
      "condition": "Buen estado",
      "price": 200000,
      "status": "Disponible",
      "image": "images/items/EST-134.jpg"
    },
    {
      "id": "EST-135",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Muebles",
      "name": "2 Banquetas de madera",
      "description": "Banquetas de barra",
      "quantity": 2,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": "Disponible",
      "image": "images/items/EST-135.jpg"
    },
    {
      "id": "EST-143",
      "room": "Cocina",
      "roomSlug": "cocina",
      "category": "Iluminación",
      "name": "Lamparas establo",
      "description": "Lampara establo rojas",
      "quantity": 1,
      "measures": null,
      "condition": null,
      "price": 30000,
      "status": "Disponible",
      "image": "images/items/EST-143.jpg"
    },
    {
      "id": "EST-136",
      "room": "Jardín / Parque",
      "roomSlug": "jardin-parque",
      "category": "Juegos",
      "name": "Juego de casita y hamaca",
      "description": "Juego de casita y amaca de madera",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 500000,
      "status": null,
      "image": "images/items/EST-136.jpg"
    },
    {
      "id": "EST-137",
      "room": "Jardín / Parque",
      "roomSlug": "jardin-parque",
      "category": "Juegos",
      "name": "Juego hamacas y tobogan nuevo",
      "description": "Juego hamacas y tobogan nuevo",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 400000,
      "status": null,
      "image": "images/items/EST-137.jpg"
    },
    {
      "id": "EST-138",
      "room": "Jardín / Parque",
      "roomSlug": "jardin-parque",
      "category": "Juegos",
      "name": "Colchoneta vieja",
      "description": "Colchoneta vieja",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 100000,
      "status": null,
      "image": "images/items/EST-138.jpg"
    },
    {
      "id": "EST-139",
      "room": "Fogón",
      "roomSlug": "fogon",
      "category": "Fogón",
      "name": "Tacho de basura de hierro",
      "description": "Tacho de basura de hierro",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 50000,
      "status": null,
      "image": "images/items/EST-139.jpg"
    },
    {
      "id": "EST-140",
      "room": "Fogón",
      "roomSlug": "fogon",
      "category": "Fogón",
      "name": "Parrilla",
      "description": "parrilla usada",
      "quantity": 1,
      "measures": null,
      "condition": "Buen estado",
      "price": 20000,
      "status": null,
      "image": null
    },
    {
      "id": "EST-141",
      "room": "Fogón",
      "roomSlug": "fogon",
      "category": "Fogón",
      "name": "4 bancos de madera",
      "description": "Cuatro bancos de madera",
      "quantity": 4,
      "measures": null,
      "condition": "Buen estado",
      "price": 1000000,
      "status": null,
      "image": "images/items/EST-141.jpg"
    },
    {
      "id": "EST-142",
      "room": "Fogón",
      "roomSlug": "fogon",
      "category": "Fogón",
      "name": "2 bancos de madera coloniales",
      "description": "Bancos de madera coloniales",
      "quantity": 2,
      "measures": null,
      "condition": "Buen estado",
      "price": 400000,
      "status": null,
      "image": "images/items/EST-142.jpg"
    }
  ]
};
